---
abstract: "Read data file definitions stored as XML\r"
author:
  - 'Jeffrey Ray Hallock <jeffrey.hallock@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-File-Map
requires:
  Moose: 0
  MooseX::SemiAffordanceAccessor: 0
  MooseX::StrictConstructor: 0
  XML::LibXML: 0
version: 0.02.1
